# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: graph.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'graph.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgraph.proto\x12\x05Graph\"\x07\n\x05\x45mpty\"\x16\n\x06Vertex\x12\x0c\n\x04vert\x18\x01 \x01(\t\"?\n\x04\x45\x64ge\x12\x19\n\x02to\x18\x01 \x01(\x0b\x32\r.Graph.Vertex\x12\x1c\n\x05start\x18\x02 \x01(\x0b\x32\r.Graph.Vertex\"(\n\x08\x45\x64geList\x12\x1c\n\x05\x65\x64ges\x18\x01 \x03(\x0b\x32\r.Graph.Vertex\"\"\n\x0egetAllResponse\x12\x10\n\x08response\x18\x01 \x03(\t\"\x1d\n\x0c\x45\x64geResponse\x12\r\n\x05\x65\x64ges\x18\x01 \x01(\t\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t\"I\n\x08Multiple\x12\x11\n\x07message\x18\x01 \x01(\tH\x00\x12 \n\x05\x65\x64ges\x18\x02 \x01(\x0b\x32\x0f.Graph.EdgeListH\x00\x42\x08\n\x06result\"\x13\n\x05YesNo\x12\n\n\x02tf\x18\x01 \x01(\x08\x32\xbd\x05\n\x05Graph\x12\x35\n\x0egetAllVertices\x12\x0c.Graph.Empty\x1a\x15.Graph.getAllResponse\x12\x32\n\x0bgetAllEdges\x12\x0c.Graph.Empty\x1a\x15.Graph.getAllResponse\x12+\n\taddVertex\x12\r.Graph.Vertex\x1a\x0f.Graph.Response\x12+\n\x07\x61\x64\x64\x45\x64ge\x12\x0b.Graph.Edge\x1a\x13.Graph.EdgeResponse\x12.\n\x0cremoveVertex\x12\r.Graph.Vertex\x1a\x0f.Graph.Response\x12*\n\nremoveEdge\x12\x0b.Graph.Edge\x1a\x0f.Graph.Response\x12(\n\thasVertex\x12\r.Graph.Vertex\x1a\x0c.Graph.YesNo\x12$\n\x07hasEdge\x12\x0b.Graph.Edge\x1a\x0c.Graph.YesNo\x12\x34\n\x0cgetNeighbors\x12\r.Graph.Vertex\x1a\x15.Graph.getAllResponse\x12(\n\x07hasPath\x12\x0f.Graph.EdgeList\x1a\x0c.Graph.YesNo\x12\'\n\x07getPath\x12\x0b.Graph.Edge\x1a\x0f.Graph.Multiple\x12,\n\x0cshortestPath\x12\x0b.Graph.Edge\x1a\x0f.Graph.Multiple\x12\x31\n\nprintGraph\x12\x0c.Graph.Empty\x1a\x15.Graph.getAllResponse\x12)\n\x08Shutdown\x12\x0c.Graph.Empty\x1a\x0f.Graph.Response\x12.\n\rClientConnect\x12\x0c.Graph.Empty\x1a\x0f.Graph.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'graph_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=22
  _globals['_EMPTY']._serialized_end=29
  _globals['_VERTEX']._serialized_start=31
  _globals['_VERTEX']._serialized_end=53
  _globals['_EDGE']._serialized_start=55
  _globals['_EDGE']._serialized_end=118
  _globals['_EDGELIST']._serialized_start=120
  _globals['_EDGELIST']._serialized_end=160
  _globals['_GETALLRESPONSE']._serialized_start=162
  _globals['_GETALLRESPONSE']._serialized_end=196
  _globals['_EDGERESPONSE']._serialized_start=198
  _globals['_EDGERESPONSE']._serialized_end=227
  _globals['_RESPONSE']._serialized_start=229
  _globals['_RESPONSE']._serialized_end=256
  _globals['_MULTIPLE']._serialized_start=258
  _globals['_MULTIPLE']._serialized_end=331
  _globals['_YESNO']._serialized_start=333
  _globals['_YESNO']._serialized_end=352
  _globals['_GRAPH']._serialized_start=355
  _globals['_GRAPH']._serialized_end=1056
# @@protoc_insertion_point(module_scope)
